ENT.Type 			= "anim"
ENT.Base 			= "base_entity"
ENT.PrintName		= "Power Pylon"
ENT.Author			= "Tampy"
ENT.Purpose			= "A power pylon. It conducts electricity."
ENT.Category		= "Aftershock"
ENT.Spawnable		= false
ENT.AS_OwnableObject = true
ENT.AS_Conductor = true