AddCSLuaFile()

SWEP.Base = "armor_base"
SWEP.Category = "Aftershock - Armors"
SWEP.PrintName = "Bandit Armor"
SWEP.Spawnable = false

SWEP.ASID = "armor_bandit"
SWEP.ModelOverride = { --Model override should only be used in the case where players with one model need to reference a specific one.
    ["models/player/group01/female_01.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group01/female_01.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group02/female_01.mdl"] = "models/armor/bandit_female.mdl",
    ["models/player/group01/female_02.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group01/female_02.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group02/female_02.mdl"] = "models/armor/bandit_female.mdl",
    ["models/player/group01/female_03.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group01/female_03.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group02/female_03.mdl"] = "models/armor/bandit_female.mdl",
    ["models/player/group01/female_04.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group01/female_04.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group02/female_04.mdl"] = "models/armor/bandit_female.mdl",
    ["models/player/group01/female_05.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group01/female_07.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group02/female_07.mdl"] = "models/armor/bandit_female.mdl",
    ["models/player/group01/female_06.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group01/female_06.mdl"] = "models/armor/bandit_female.mdl",
    ["models/kayf/humans/group02/female_06.mdl"] = "models/armor/bandit_female.mdl",
    ["models/player/group01/male_01.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_01.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_01.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_02.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group02/male_02.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_02.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_02.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_03.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_03.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_03.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_04.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group02/male_04.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_04.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_05.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_05.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_05.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_06.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group02/male_06.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_06.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_06.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_07.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_07.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_07.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_08.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group02/male_08.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_08.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_08.mdl"] = "models/armor/bandit.mdl",
    ["models/player/group01/male_09.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group01/male_09.mdl"] = "models/armor/bandit.mdl",
    ["models/kayf/humans/group02/male_09.mdl"] = "models/armor/bandit.mdl",
    ["default"] = "models/armor/bandit.mdl", --This is important. If we cannot find a reference for us, we default to this one in case.
}